packages:
  - packages/*
  - apps/*

allowBuilds:
  "@vscode/vsce-sign": false
  esbuild: true
  keytar: false

onlyBuiltDependencies:
  - esbuild

overrides:
  "@ilic/compiler-wasm": file:../ilic-fork/packages/compiler-wasm
  "@ilic/tools": file:../ilic-fork/packages/tools
  "minimatch@5.1.9>brace-expansion": 5.0.8
